version: '3.9'
services:
    nginx:
        image: docker.io/nginx:stable-alpine
        volumes:
            - ./nginx-docker.conf.template:/etc/nginx/templates/default.conf.template:ro
            - static_files:/static:ro
            - sockets:/sockets
        ports:
            - '${PORT:-8000}:8000'
        depends_on:
            - secretgraph
        environment:
            SCHEME_HEADER: '${SCHEME_HEADER:-$$scheme}'
    secretgraph:
        extends:
            file: docker-compose.base.yml
            service: secretgraph
        volumes:
            - sockets:/sockets
            - static_files:/static
        environment:
            USER_GROUP: '101'

volumes:
    sockets:
    static_files:
