version: 3.9
services:
    nginx:
        image: docker.io/nginx:stable-alpine
        volumes:
            - ./nginx-docker.conf.template:/etc/nginx/templates/default.conf.template:ro
            - static_files:/static:ro
            - sockets:/sockets
        ports:
            - '8000:8000'
        depends_on:
            - secretgraph
        environment:
            SCHEME_HEADER: '$scheme'
    secretgraph:
        init: true
        build:
            context: .
        volumes:
            - secretgraph:/var/lib/secretgraph
            - static_files:/static
            - sockets:/sockets
        environment:
            USER_GROUP: '101'
            SECRET_KEY: 'changeme'
            ALLOWED_HOSTS: 'localhost'

volumes:
    static_files:
    sockets:
    secretgraph:
