[tool.poetry]
name = "secretgraph"
description = "A secure, decentral identity graph"
version = "0.1"
license = "MIT"
authors = ["Alexander Kaftan"]
homepage = "https://spkcspider.net"
readme = "README.md"
repository = "https://github.com/devkral/secretgraph"
classifiers = [
  "Development Status :: 4 - Beta",
  "Framework :: Django",
  "Intended Audience :: System Administrators",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: POSIX",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content :: Content Management System",
  "Topic :: Internet :: WWW/HTTP :: WSGI :: Application"
]

keywords = [
  "online identity", "decentral networks"
]

[tool.poetry.dependencies]
python = ">=3.8, <4"
django = '>=3.0'
cryptography = "*"
rdflib = '*'
requests = "*"
certifi = "*"
graphene-protector = {version="*", optional = true}
graphene-django = {version="*", optional = true}
graphene-file-upload = {version="*", optional = true}
flipflop = {version="*", optional = true}
mysqlclient = {version="*", optional = true}
django-mysql = {version="*", optional = true}
psycopg2 = {version="*", optional = true}
django-webtest = {version="*", optional = true}
WSGIProxy2 = {version="*", optional = true}
django-manifest-loader = {version="*", optional = true}
django-fast-ratelimit = {version="*", optional = true}


[tool.poetry.dev-dependencies]
graphene-protector = ">=0.4.0beta0"
graphene-django = '*'
graphene-file-upload = "*"
django-extensions = '*'
Werkzeug = '*'
pylint = "*"
rope = "*"
django-manifest-loader = "*"
django-fast-ratelimit = "*"


[tool.poetry.extras]
server = ["graphene-django", "graphene-protector", "graphene-file-upload", "django-fast-ratelimit"]
fastcgi = ["flipflop"]
postgresql = ["psycopg2"]
mysql = ["mysqlclient", "django-mysql"]
#tasks = ["celery", "sqlalchemy"]
test = [
  "django-webtest",
  "WSGIProxy2",
  "graphene-django",
  "graphene-file-upload",
  "django-fast-ratelimit"
]

[tool.tox]
legacy_tox_ini = """
[tox]
minversion = 3.4.0
isolated_build = True
envlist = py{36,37,38}-django{30,master}-{sqlite3,postgresql,mysql}
extras =
  test

[testenv]
whitelist_externals =
  psql
commands =
  !postgresql: python -Wd ./manage.py test tests
  postgresql: python -Wd ./manage.py test --keepdb tests
  postgresql: psql -c 'drop database secretgraph_tests;' -U postgres


setenv =
    PYTHONDONTWRITEBYTECODE=1
    sqlite3: DJANGO_SETTINGS_MODULE=testsettings.test_sqlite3
    postgresql: DJANGO_SETTINGS_MODULE=testsettings.test_postgresql
    mysql: DJANGO_SETTINGS_MODULE=testsettings.test_mysql

deps =
  django30: Django>=3.0,<3.1
  djangomaster: https://github.com/django/django/archive/master.zip
  postgresql: psycopg2-binary
  mysql: mysqlclient
  mysql: django-mysql

"""

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
