# Generated by Django 3.0.5 on 2020-04-06 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import secretgraph.server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('flexid', models.UUIDField(blank=True, null=True, unique=True)),
                ('public_info', models.TextField()),
                ('public', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('flexid', models.UUIDField(blank=True, null=True, unique=True)),
                ('key_hash', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nonce', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=secretgraph.server.models.get_file_path)),
                ('info_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretgraph_base.Component')),
            ],
        ),
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('tag', models.TextField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='secretgraph_base.Content')),
            ],
        ),
        migrations.CreateModel(
            name='ContentReference',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('delete_recursive', models.BooleanField(blank=True, default=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='secretgraph_base.Content')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by', to='secretgraph_base.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('key_hash', models.CharField(max_length=255)),
                ('nonce', models.CharField(max_length=255)),
                ('value', models.BinaryField()),
                ('start', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('stop', models.DateTimeField(blank=True, null=True)),
                ('accessed', models.BooleanField(blank=True, default=False)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='secretgraph_base.Component')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_action', to='secretgraph_base.Content')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contentreference',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, source=django.db.models.expressions.F('target')), name='contentreference_no_self_ref'),
        ),
        migrations.AddConstraint(
            model_name='contentreference',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'name'), name='contentreference_unique'),
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(fields=('info_hash', 'component_id'), name='unique_content'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.CheckConstraint(check=models.Q(('start__lte', django.db.models.expressions.F('stop')), ('stop__isnull', True), _connector='OR'), name='action_order'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.CheckConstraint(check=models.Q(('start__isnull', False), ('stop__isnull', False), _connector='OR'), name='action_exist'),
        ),
    ]
