# Generated by Django 4.2.3 on 2023-07-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secretgraph", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clustergroup",
            name="userSelectable",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a", "None"),
                    ("b", "Unrestricted"),
                    ("c", "Selectable"),
                    ("d", "Deselectable"),
                    ("e", "Initial Modifyable"),
                ],
                default="a",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="netgroup",
            name="userSelectable",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a", "None"),
                    ("b", "Unrestricted"),
                    ("c", "Selectable"),
                    ("d", "Deselectable"),
                    ("e", "Initial Modifyable"),
                ],
                default="a",
                max_length=1,
            ),
        ),
    ]
