# Generated by Django 4.2 on 2023-04-27 00:40

import django.core.validators
from django.db import migrations, models
import secretgraph.server.validators


class Migration(migrations.Migration):
    dependencies = [
        ("secretgraph", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GlobalGroupProperty",
            new_name="SGroupProperty",
        ),
        migrations.CreateModel(
            name="ClusterGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            secretgraph.server.validators.SafeNameValidator(),
                            django.core.validators.MinLengthValidator(1),
                        ],
                    ),
                ),
                ("description", models.TextField()),
                ("hidden", models.BooleanField(blank=True, default=False)),
                (
                    "clusters",
                    models.ManyToManyField(
                        help_text="cluster groups: groups for cluster permissions and injected keys",
                        related_name="groups",
                        to="secretgraph.cluster",
                    ),
                ),
                (
                    "injectedKeys",
                    models.ManyToManyField(
                        limit_choices_to={
                            "cluster_id": 0,
                            "type": "PublicKey",
                        },
                        related_name="injectedFor",
                        to="secretgraph.content",
                    ),
                ),
                (
                    "properties",
                    models.ManyToManyField(
                        limit_choices_to=models.Q(
                            ("name__startswith", "manage_"), _negated=True
                        ),
                        related_name="clusterGroups",
                        to="secretgraph.sgroupproperty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            secretgraph.server.validators.SafeNameValidator(),
                            django.core.validators.MinLengthValidator(1),
                        ],
                    ),
                ),
                ("description", models.TextField()),
                (
                    "nets",
                    models.ManyToManyField(
                        help_text="cluster groups: groups for permissions",
                        related_name="groups",
                        to="secretgraph.net",
                    ),
                ),
                (
                    "properties",
                    models.ManyToManyField(
                        related_name="netGroups",
                        to="secretgraph.sgroupproperty",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="GlobalGroup",
        ),
    ]
