# Generated by Django 4.2.3 on 2023-07-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "secretgraph",
            "0002_clustergroup_userselectable_netgroup_userselectable",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="netgroup",
            name="hidden",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
