# Generated by Django 4.2.3 on 2023-07-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secretgraph", "0004_alter_sgroupproperty_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clustergroup",
            name="clusters",
            field=models.ManyToManyField(
                blank=True,
                help_text="cluster groups: groups for cluster permissions and injected keys",
                related_name="groups",
                to="secretgraph.cluster",
            ),
        ),
    ]
