# Generated by Django 4.2.4 on 2023-08-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secretgraph", "0005_alter_clustergroup_clusters"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="locked",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="action",
            name="nonce",
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name="content",
            name="nonce",
            field=models.CharField(blank=True, default="", max_length=48),
        ),
    ]
