# Generated by Django 5.0.2 on 2024-02-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretgraph', '0006_content_locked_alter_action_nonce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file_accessed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
