# Generated by Django 5.0.2 on 2024-02-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secretgraph", "0007_alter_content_file_accessed"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="cryptoParameters",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
