# Generated by Django 5.0.2 on 2024-02-13 22:56

from django.db import migrations


def forwards(apps, schema_editor):
    Content = apps.get_model("secretgraph", "Content")
    for content in Content.objects.exclude(nonce="").filter(cryptoParameters=""):
        content.cryptoParameters = f"AESGCM:{content.nonce}"
        content.nonce = ""
        content.save(update_fields=["cryptoParameters", "nonce"])


def backwards(apps, schema_editor):
    Content = apps.get_model("secretgraph", "Content")
    for content in Content.objects.exclude(cryptoParameters__startswith="AESGCM:"):
        content.nonce = content.cryptoParameters.split(":", 1)[1]
        content.cryptoParameters = ""
        content.save(update_fields=["cryptoParameters", "nonce"])


class Migration(migrations.Migration):
    dependencies = [
        ("secretgraph", "0008_content_cryptoparams"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
