from django.utils.translation import gettext_noop as _

# WARNING AUTOGENERATED

# client/src/theme.tsx: 1026
_('Draft')

# client/src/theme.tsx: 1082
# client/src/theme.tsx: 1304
_('Protected')

# client/src/theme.tsx: 1142
_('Sensitive')

# client/src/theme.tsx: 1199
# client/src/theme.tsx: 1361
_('Public')

# client/src/theme.tsx: 1416
_('Trusted')

# client/src/theme.tsx: 1473
_('Required')

# client/src/editors/index.tsx: 350
_('Cluster')

# client/src/editors/index.tsx: 501
_('File')

# client/src/editors/index.tsx: 646
_('Text')

# client/src/editors/index.tsx: 796
# client/src/editors/index.tsx: 917
_('Keys')

# client/src/editors/index.tsx: 1060
_('Config')

# client/src/editors/index.tsx: 1243
_('ChannelStore')

# client/src/editors/index.tsx: 1433
_('Workday')

# client/src/editors/index.tsx: 1587
_('Custom')

# client/src/editors/index.tsx: 1740
_('Loading')

# rdf-editors/src/editors/index.tsx: 182
_('Source')

# rdf-editors/src/editors/index.tsx: 364
_('Contact')

# rdf-editors/src/editors/index.tsx: 548
_('Postbox')

# rdf-editors/src/editors/index.tsx: 732
_('Message')

# ui-components/src/forms/SplittedGroupSelectList.tsx: 1825
_('topics')

# ui-components/src/forms/SplittedGroupSelectList.tsx: 2196
_('misc')
