# WARNING AUTOGENERATED

serverConfigQuery = """
    query serverSecretgraphConfigQuery {
        secretgraph {
            config {
                id
                hashAlgorithms
                asymmetricEncryptionAlgorithms
                signatureAlgorithms
                maxRelayResults
                clusterGroups {
                    name
                    description
                    userSelectable
                    hidden
                    properties
                    injectedKeys {
                        link
                        hash
                    }
                }
                netGroups {
                    name
                    description
                    userSelectable
                    hidden
                    properties
                }
                canDirectRegister
                registerUrl
                loginUrl
            }
            activeUser
        }
    }
"""

serverConfigQueryWithPermissions = """
    query serverSecretgraphConfigWithPermissionsQuery(
        $authorization: [String!]
    ) {
        secretgraph(authorization: $authorization) {
            permissions
            config {
                id
                hashAlgorithms
                asymmetricEncryptionAlgorithms
                signatureAlgorithms
                maxRelayResults
                clusterGroups {
                    name
                    description
                    userSelectable
                    hidden
                    properties
                    injectedKeys {
                        link
                        hash
                    }
                }
                netGroups {
                    name
                    description
                    userSelectable
                    hidden
                    properties
                }
                canDirectRegister
                registerUrl
                loginUrl
            }
            activeUser
        }
    }
"""

serverLogout = """
    mutation serverLogoutMutation {
        secretgraph {
            logoutUser
        }
    }
"""
